about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/


package:
  name: "bioformats2raw"
  version: "0.2.1"

build:
  noarch: generic
  number: 1

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v0.2.1/bioformats2raw-0.2.1.zip
  sha256: 

requirements:
  host:
  run:
    - openjdk =11

test:
  commands:
    - bioformats2raw a.fake output

extra:
  recipe-maintainers:
    - ome
