on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    steps:
      # Conda is installed in the base VM but it has problems on Windows
      # Use https://github.com/marketplace/actions/setup-miniconda instead
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: "3.8"

      - run: env
        shell: bash

      - name: Set conda-bld output folder to make it easier to find artifacts
        id: condablddir
        # On Windows /conda-bld and \\conda-bld work here but fail later
        # c:\\conda-bld seems to work.... for now
        run: |
          if [ ${{ matrix.os }} = windows-latest ]; then
            echo "::set-output name=condabld::c:\\conda-bld"
          else
            echo "::set-output name=condabld::$HOME/conda-bld"
          fi
        shell: bash

      - run: |
          echo "${{ steps.condablddir.outputs.condabld }}"
          mkdir ${{ steps.condablddir.outputs.condabld }}
          conda config --set conda_build.output_folder ${{ steps.condablddir.outputs.condabld }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Install conda build
        run: conda install -y -q conda-build conda-verify

      - name: Build bioformats2raw-libs
        run: conda build bioformats2raw-libs
      - name: Build bioformats2raw
        run: conda build bioformats2raw
      - run: ls -R "${{ steps.condablddir.outputs.condabld }}"

      # We want
      # - bioformats2raw-libs noarch from one job
      # - bioformats2raw *-64 from all jobs

      - uses: actions/upload-artifact@v2
        with:
          path: "${{ steps.condablddir.outputs.condabld }}/noarch/bioformats2raw-libs-*"
          if-no-files-found: error
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v2
        with:
          # {linux,osx,win}-64
          path: "${{ steps.condablddir.outputs.condabld }}/*-64/bioformats2raw-*"
          if-no-files-found: error

  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:

      # Since we just need the client use a python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install anaconda-client
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R

      - name: Upload to Anaconda Cloud
        run: |
          anaconda whoami
          for f in artifact/bioformats2raw* artifact/*/bioformats2raw*; do
            anaconda upload --user ${ANACONDA_USER} $f
          done
        env:
          ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
